import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/context/UserContext";
import Footer from "@/components/footer";

import { Poppins } from "next/font/google";
const pop = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"],
});
export const metadata: Metadata = {
    title: "FE Next",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={pop.className}>
                <UserProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </UserProvider>
            </body>
        </html>
    );
}
